#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 22 18:32:59 2020

@author: Kimeunna
"""


from PIL import Image
import openslide
import os
import cv2
import glob
import sys 

xylist=[]
index=0
idx=0
File_Name=[]

os.chdir("/Users/Kimeunna/Dropbox/아론티어/abnormal chromosome/ex")
files=glob.glob('annotation_txt/*.txt')
for file in files:
    f=open(file,'r',encoding='UTF-8')
    for row in f:
        if '/Volumes' in row: 
            wsi_path_bef=row
            wsi_path_aft=wsi_path_bef.replace("TOSHIBA EXT 1","TOSHIBA EXT").rstrip()
            try:
                slide = openslide.OpenSlide(wsi_path_aft)
                txtfile_name=row.split('/')[4].replace(".mrxs\n","")
            except:
                print("There is no file named %s"%(wsi_path_aft))
        elif '[Point:' in row: 
            xy=row.split(', Point:')[0]
            xynum= xy.split(': ')[1]
            xloc=int(round(float(xynum.split(',')[0])))
            yloc=int(round(float(xynum.split(',')[1])))
            xyloc=(xloc,yloc)
       
            image=slide.read_region(xyloc,0,(1024,1024))
            #save_dir='/Users/Kimeunna/Dropbox/아론티어/abnormal chromosome/ex'
            imagefilename=str(txtfile_name)+str(index)
            image.save(f'{imagefilename}.png')
            index=index+1                
       
## directory 에 맞춰서 저장하는 것부터 다시 하기
