#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 15 19:19:39 2020

@author: Kimeunna
"""


import os
import glob
import mritopng 

os.chdir('/Users/Kimeunna/Dropbox/아론티어')
file_list=glob.glob('SRS00000/*')

file_list[1]

# Convert a single file with auto-contrast
mritopng.convert_file(file_list[1],'/Users/Kimeunna/Dropbox/아론티어/aaa.png')


# Convert a whole folder recursively
mritopng.convert_folder('SRS00000/','/Users/Kimeunna/Dropbox/아론티어/test0/') 
                        
