#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 15 19:19:39 2020

@author: Kimeunna
"""


import os
import glob
import mritopng 

os.chdir('/Users/Kimeunna/Dropbox/아론티어')
file_list=glob.glob('SRS00000/*')

file_list[1]

# Convert a single file with auto-contrast
mritopng.convert_file(file_list[1],'/Users/Kimeunna/Dropbox/아론티어/aaa.png')


# Convert a whole folder recursively
mritopng.convert_folder('SRS00000/','/Users/Kimeunna/Dropbox/아론티어/test0/') 

# 폴더 안에 있는 파일 모두 옮기기 for 문을 써서.  
for i in [’SRS00001’,’SRS00002’]:
    mritopng.convert_folder(i,’C:/users/arontier/desktop/{}/‘.format(i))
