#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jul 13 17:10:30 2020

@author: Kimeunna
"""
import os
os.chdir("/Volumes/My Passport/placenta_result_0625/eval")
new_f = open('project5.qpproj', 'w')

with open('project.qpproj', 'r') as f:
    a = f.read().replace('TOSHIBA EXT', 'My Passport')
    new_f.write(a)
new_f.close()




import os
os.chdir("/Users/Kimeunna/Dropbox/python") # Spyder 로 실행하는 경우 
new_f = open('project5.qpproj','w')
print(new_f)
with open('project.qpproj') as f:
    a=f.read().replace('TOSHIBA EXT 2','TOSHIBA EXT 1')
    new_f.write(a)
new_f.close()
